Repository prgrms-fe-devcourse/FEDC2_2JAVATAYO_Dongyoung, pull requests merged in 2022-06, with the labels that each got.

#47 Feature/#11
  .github/PULL_REQUEST_TEMPLATE/kr.md
  package-lock.json
  package.json
  src/App.tsx
  src/pages/404.tsx
  src/pages/create.tsx
  src/pages/detail.tsx
  src/pages/edit.tsx
  src/pages/home.tsx
  src/pages/profile.tsx
  src/pages/result.tsx
  src/pages/signIn.tsx
  src/pages/signUp.tsx
  src/routes/Router.tsx
  tsconfig.json
Labels: Feature

#50 docs: change default pull request template
  .github/pull_request_template.md
Labels: Documentation

#69 ✨feat: ProfileImage 공통 컴포넌트 구현
  src/components/common/ProfileImage/ProfileImage.stories.tsx
  src/components/common/ProfileImage/defaultProfileImage.png
  src/components/common/ProfileImage/index.tsx
  src/components/common/ProfileImage/style.tsx
  src/components/common/index.tsx
Labels: Feature, 유현

#73 :sparkles: feat: Cascader구현
  src/components/create/Cascader/Cascader.tsx
  src/components/create/Cascader/index.tsx
  src/pages/create.tsx
Labels: Feature

#77 ✨ feat: AppLayout 컴포넌트 추가
  src/components/common/AppLayout/AppLayout.stories.tsx
  src/components/common/AppLayout/AppLayout.tsx
  src/components/common/AppLayout/index.tsx
  src/components/common/AppLayout/style.tsx
Labels: Feature

#76 :sparkles: feat: DatePicker 구현
  src/components/create/DatePicker/DatePicker.tsx
  src/components/create/DatePicker/index.tsx
  src/pages/create.tsx
Labels: Feature

#85 :sparkles: feat: SelectBox 구현
  src/components/create/SelectBox/SelectBox.tsx
  src/components/create/SelectBox/index.tsx
  src/components/create/SelectBox/style.tsx
  src/pages/create.tsx
Labels: Feature

#71 ✨ feat: Input, Label, ErrorMessage 컴포넌트 생성
  src/components/common/ErrorMessage/ErrorMessage.stories.tsx
  src/components/common/ErrorMessage/ErrorMessage.tsx
  src/components/common/ErrorMessage/index.tsx
  src/components/common/ErrorMessage/style.tsx
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/index.tsx
  src/components/common/Input/style.tsx
  src/components/common/Label/Label.stories.tsx
  src/components/common/Label/Label.tsx
  src/components/common/Label/index.tsx
  src/components/common/Label/style.tsx
Labels: Feature

#95 ✨ feat: API 추가
  .gitignore
  package-lock.json
  package.json
  src/types/apis.ts
  src/types/model.ts
  src/utils/apis/auth.ts
  src/utils/apis/channel.ts
  src/utils/apis/comment.ts
  src/utils/apis/common.ts
  src/utils/apis/follow.ts
  src/utils/apis/index.ts
  src/utils/apis/like.ts
  src/utils/apis/notification.ts
  src/utils/apis/post.ts
  src/utils/apis/search.ts
  src/utils/apis/setting.ts
  src/utils/apis/user.ts
  src/utils/storage.ts
Labels: Feature

#86 :sparkles: feat: skill.ts 구현
  src/constants/skill.ts
Labels: Feature

#83 ✨ feat: SkillIcon 공통 컴포넌트 구현
  .gitignore
  .storybook/main.js
  craco.config.js
  public/assets/icons/icon_angular.svg
  public/assets/icons/icon_appwrite.svg
  public/assets/icons/icon_bootstrap.svg
  public/assets/icons/icon_cpp.svg
  public/assets/icons/icon_django.svg
  public/assets/icons/icon_express.svg
  public/assets/icons/icon_fast_api.svg
  public/assets/icons/icon_figma.svg
  public/assets/icons/icon_firebase.svg
  public/assets/icons/icon_flutter.svg
  public/assets/icons/icon_gatsby.svg
  public/assets/icons/icon_graph_ql.svg
  public/assets/icons/icon_html5.svg
  public/assets/icons/icon_java.svg
  public/assets/icons/icon_julia.svg
  public/assets/icons/icon_kotlin.svg
  public/assets/icons/icon_lua.svg
  public/assets/icons/icon_mongo_db.svg
  public/assets/icons/icon_mui.svg
  public/assets/icons/icon_my_sql.svg
  public/assets/icons/icon_nest_js.svg
  public/assets/icons/icon_next_js.svg
  public/assets/icons/icon_node_js.svg
  public/assets/icons/icon_nuxt_js.svg
  public/assets/icons/icon_oracle.svg
  public/assets/icons/icon_postgre_sql.svg
  public/assets/icons/icon_python.svg
  public/assets/icons/icon_r.svg
  public/assets/icons/icon_react.svg
  public/assets/icons/icon_recoil.svg
  public/assets/icons/icon_redux.svg
  public/assets/icons/icon_rn.svg
  public/assets/icons/icon_sass.svg
  public/assets/icons/icon_spring.svg
  public/assets/icons/icon_svelte.svg
  public/assets/icons/icon_swift.svg
  public/assets/icons/icon_tailwind.svg
  public/assets/icons/icon_tensor_flow.svg
  public/assets/icons/icon_type_script.svg
  public/assets/icons/icon_vue.svg
  public/assets/icons/icon_zeplin.svg
  src/components/common/SkillIcon/SkillIcon.stories.tsx
  src/components/common/SkillIcon/index.tsx
  src/components/common/SkillIcon/style.tsx
  src/components/common/index.tsx
  src/hooks/index.tsx
  src/hooks/useHover.stories.js
  src/hooks/useHover.ts
  src/hooks/useXXX.ts
Labels: Feature

#80 ✨ feat: Button 공통 컴포넌트 구현
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/style.tsx
Labels: Feature

#103 ✨ feat: CoverImage 컴포넌트 구현
  src/assets/imgs/profile_default_cover.png
  src/components/profile/CoverImage/index.tsx
  src/components/profile/CoverImage/style.tsx
  src/components/profile/index.tsx
  src/pages/profile.tsx
Labels: Feature

#118 🐛 fix: process.env 수정
  src/utils/apis/common.ts
Labels: Bug

#107 ✨ feat: useClickAway 훅 추가
  .storybook/main.js
  src/hooks/useClickAway.stories.tsx
  src/hooks/useClickAway.ts
Labels: Feature

#119 🐛 fix: path alias 설정이 적용되지 않던 문제
  craco.config.js
  package-lock.json
  package.json
  src/components/common/Footer/Footer.tsx
  src/components/common/SkillIcon/index.tsx
  src/components/profile/CoverImage/index.tsx
  tsconfig.json
  tsconfig.paths.json
Labels: Bug

#94 ✨ feat: Header 컴포넌트 구현 (임시)
  src/assets/logos/Logo.svg
  src/components/common/Header/Header.stories.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/index.tsx
  src/components/common/Header/style.tsx
Labels: Feature, 미완성

#113 :sparkles: feat: PartBox 구현
  src/components/create/Cascader/Cascader.jsx
  src/components/create/PartBox/PartBox.jsx
  src/components/create/PartBox/index.tsx
  src/components/create/PartBox/style.tsx
  src/components/create/Select/Select.tsx
  src/constants/skill.ts
  src/pages/create.tsx
Labels: Feature

#124 ✨feat: AppLayout 컴포넌트 추가 작업완료
  src/components/common/AppLayout/AppLayout.stories.tsx
  src/components/common/AppLayout/AppLayout.tsx
  src/components/common/AppLayout/style.tsx
  src/styles/reset.tsx
Labels: Feature, 남경

#89 ✨ feat: Card 컴포넌트 추가
  src/assets/icons/icon_heart.svg
  src/assets/icons/icon_heart_fill.svg
  src/components/common/Card/Card.stories.tsx
  src/components/common/Card/Card.tsx
  src/components/common/Card/index.tsx
  src/components/common/Card/style.tsx
  src/components/common/SkillIcon/SkillIcon.stories.tsx
  src/components/common/SkillIcon/style.tsx
Labels: Feature, 남경, 미완성

#93 ✨ feat: Textarea 공통 컴포넌트 구현
  src/components/common/Textarea/Textarea.stories.tsx
  src/components/common/Textarea/Textarea.tsx
  src/components/common/Textarea/index.tsx
  src/components/common/Textarea/style.tsx
Labels: Feature

#129 🐛 fix: type오류로 임시 dummy 데이터 추가
  src/components/common/Card/Card.stories.tsx
  src/components/common/Card/Card.tsx
Labels: Bug, 남경

#126 :sparkles: feat: create page 목업
  src/components/common/AppLayout/AppLayout.tsx
  src/components/create/PartBox/style.tsx
  src/pages/create.tsx
  src/pages/create/create.tsx
  src/pages/create/index.tsx
  src/pages/create/style.tsx
  src/routes/Router.tsx
Labels: Feature

#123 ✨ feat: Modal 컴포넌트 구현
  src/assets/icons/icon_close.svg
  src/components/profile/Modal/Modal.stories.tsx
  src/components/profile/Modal/index.tsx
  src/components/profile/Modal/style.tsx
  src/components/profile/index.tsx
  src/hooks/index.tsx
Labels: Feature

#128 🐛 fix: 스토리북 path alias 적용 문제
  .storybook/main.js
  package-lock.json
  package.json
  tsconfig.json
  tsconfig.paths.json
Labels: Bug

#130 ✨ feat: home 페이지 레이아웃 설정
  src/components/common/Card/style.tsx
  src/components/home/Filter/Filter.tsx
  src/components/home/Filter/style.tsx
  src/pages/home.tsx
  src/pages/home/index.tsx
  src/pages/home/style.tsx
  src/styles/reset.tsx
Labels: Feature

#138 ✨ feat: 생성페이지 디테일 수정
  src/components/create/DatePicker/DatePicker.tsx
  src/components/create/InputBox/style.tsx
  src/components/create/Select/Select.tsx
  src/components/create/SelectBox/SelectBox.tsx
  src/components/create/SelectBox/style.tsx
  src/pages/create/create.tsx
  src/pages/create/style.tsx
Labels: Feature

#148 :sparkles: feat: blocker.js구현
  src/pages/create/create.tsx
  src/routes/Blocker.js
Labels: Feature

#150 ✨ feat: PostBody 컴포넌트 생성
  src/components/detail/PostBody/PostBody.tsx
  src/components/detail/PostBody/index.tsx
  src/components/detail/PostBody/style.tsx
  src/components/detail/PostHeader/PostSummary/style.tsx
  src/components/detail/PostHeader/style.tsx
  src/pages/detail.tsx
Labels: Feature, 우선순위: 중간

#152 ✨ feat: Tab 컴포넌트 구현
  src/components/profile/Tab/TabItem.tsx
  src/components/profile/Tab/index.tsx
  src/components/profile/Tab/style.tsx
  src/components/profile/index.tsx
  src/pages/profile/profile.tsx
Labels: Feature

#157 ✨ feat: TempLogin 컴포넌트 추가
  src/components/common/Header/Header.tsx
  src/components/common/TempLogin/index.tsx
Labels: Feature, 남경

#164 💄 style: 공통 style 수정
  src/components/common/AppLayout/style.tsx
  src/styles/reset.tsx
Labels: 남경, 우선순위: 중간

#155 ✨ feat: PostFooter 컴포넌트 생성
  src/components/common/Textarea/Textarea.tsx
  src/components/common/Textarea/style.tsx
  src/components/detail/PostFooter/Comment/Comment.tsx
  src/components/detail/PostFooter/Comment/index.tsx
  src/components/detail/PostFooter/Comment/style.tsx
  src/components/detail/PostFooter/PostFooter.tsx
  src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
  src/components/detail/PostFooter/TextareaBox/index.tsx
  src/components/detail/PostFooter/TextareaBox/style.tsx
  src/components/detail/PostFooter/index.tsx
  src/components/detail/PostFooter/style.tsx
  src/pages/detail.tsx
Labels: Feature, 우선순위: 중간

#158 ✨ feat: ProfileImageBox 컴포넌트 구현
  src/components/profile/EditIcon/index.tsx
  src/components/profile/ProfileImageBox/index.tsx
  src/components/profile/ProfileImageBox/style.tsx
  src/components/profile/index.tsx
  src/pages/profile/profile.tsx
  src/pages/profile/style.tsx
Labels: Feature

#163 ✨ feat: card컴포넌트에 데이터 입력
  src/components/common/Card/Card.stories.tsx
  src/components/common/Card/Card.tsx
  src/components/common/Card/style.tsx
  src/components/home/Filter/Filter.stories.tsx
  src/utils/Date.tsx
Labels: Feature, 우선순위: 중간

#166 ✨ feat: PartBoxList구현
  src/components/create/Cascader/Cascader.jsx
  src/components/create/PartBox/PartBox.jsx
  src/components/create/PartBoxList/PartBoxList.jsx
  src/components/create/PartBoxList/index.tsx
  src/components/create/PartBoxList/style.tsx
  src/pages/create/create.tsx
Labels: Feature

#172 💄 style: header 스타일 변경
  src/assets/icons/icon_bell.svg
  src/components/common/Header/Header.tsx
  src/components/common/Header/style.tsx
  src/components/common/TempLogin/index.tsx
Labels: Feature

#173 ✨ feat: CoverImageBox 컴포넌트 구현
  src/components/profile/CoverImageBox/index.tsx
  src/components/profile/CoverImageBox/style.tsx
  src/components/profile/ProfileImageBox/index.tsx
  src/components/profile/index.tsx
  src/pages/profile/profile.tsx
Labels: Feature

#169 :sparkles: feat: ImageUploader구현
  package-lock.json
  package.json
  src/components/create/ImageUploader/ImageUploader.tsx
  src/components/create/ImageUploader/style.tsx
  src/pages/create/create.tsx
Labels: Feature

#179 💄 style: 프로필 페이지 스타일 추가
  src/assets/icons/icon_setting.svg
  src/components/common/ImageUpload/index.tsx
  src/components/profile/CoverImageBox/index.tsx
  src/components/profile/CoverImageBox/style.tsx
  src/components/profile/EditIcon/index.tsx
  src/components/profile/EditIcon/style.tsx
  src/components/profile/ProfileImageBox/index.tsx
  src/components/profile/Tab/index.tsx
  src/components/profile/index.tsx
  src/pages/profile/profile.tsx
  src/pages/profile/style.tsx
Labels: Feature

#177 ✨feat: Like 기능 추가
  src/components/common/AppLayout/AppLayout.tsx
  src/components/common/Card/Card.tsx
  src/components/common/Header/Header.tsx
  src/components/common/LikeBtn/LikeBtn.tsx
  src/components/common/LikeBtn/index.tsx
  src/components/common/LikeBtn/style.tsx
  src/components/common/index.tsx
  src/pages/home/home.tsx
  src/pages/home/index.tsx
Labels: Feature, 남경

#183 💄 style: search 페이지 스타일 설정
  src/assets/imgs/search_banner.jpg
  src/components/common/AppLayout/AppLayout.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/style.tsx
  src/pages/home/style.tsx
  src/pages/result.tsx
  src/pages/search/index.tsx
  src/pages/search/search.tsx
  src/pages/search/style.tsx
  src/routes/Router.tsx
Labels: Feature

#187 ✨ feat: EditFullName 컴포넌트 구현
  src/components/common/Header/style.tsx
  src/components/profile/EditFullName/EditFullName.tsx
  src/components/profile/EditFullName/index.tsx
  src/components/profile/EditFullName/style.tsx
  src/components/profile/Modal/index.tsx
  src/components/profile/Modal/style.tsx
  src/components/profile/index.tsx
  src/pages/profile/profile.tsx
Labels: Feature

#191 ✨ feat: useAxiosFn, useAxios 훅 구현
  src/hooks/index.tsx
  src/hooks/useAxios.ts
  src/hooks/useAxiosFn.ts
Labels: Feature

#184 ✨ feat: 전체 post가져오기
  src/components/home/Filter/Filter.stories.tsx
  src/components/home/Filter/Filter.tsx
  src/components/home/Filter/style.tsx
  src/pages/home/home.tsx
  src/pages/search/search.tsx
  src/utils/apis/post.ts
Labels: Feature

#186 🐛 fix: likeBtn 오류 수정
  src/components/common/LikeBtn/LikeBtn.tsx
  src/styles/reset.tsx
Labels: Bug, 남경

#190 🐛 fix: getItem, removeItem 불필요한 에러 핸들링 제거
  src/utils/storage.ts
Labels: Bug

#193 ✨ feat: AuthProvider 구현
  src/App.tsx
  src/contexts/AuthProvider.tsx
Labels: Feature

#202 ✨ feat: 로그인폼 구현
  src/assets/logos/logo_favicon.svg
  src/components/create/InputBox/InputBox.tsx
  src/components/signIn/index.tsx
  src/hooks/useSignIn.tsx
  src/pages/signIn.tsx
  src/pages/signIn/index.tsx
  src/pages/signIn/signIn.tsx
  src/pages/signIn/style.tsx
  src/routes/Router.tsx
Labels: Feature

#195 ✨ feat: DropDown 컴포넌트 추가
  src/components/common/DropDown/DropDown.stories.tsx
  src/components/common/DropDown/DropDown.tsx
  src/components/common/DropDown/index.tsx
  src/components/common/DropDown/style.tsx
Labels: Feature

#194 🐛 fix: 서버 API 오류
  src/types/apis.ts
  src/utils/apis/follow.ts
  src/utils/apis/like.ts
  src/utils/apis/notification.ts
  src/utils/apis/post.ts
  src/utils/apis/user.ts
Labels: Bug

#205 ✨ feat: 상세 페이지 서버통신 구현
  src/components/common/Textarea/Textarea.tsx
  src/components/common/Textarea/style.tsx
  src/components/detail/PostBody/PostBody.tsx
  src/components/detail/PostFooter/Comment/Comment.tsx
  src/components/detail/PostFooter/PostFooter.tsx
  src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
  src/components/detail/PostHeader/PostHeader.tsx
  src/components/detail/PostHeader/PostSummary/PostSummary.tsx
  src/pages/detail.tsx
Labels: Feature, 형진

#207 ✨ feat: header에 DropDown 추가
  src/components/common/DropDown/style.tsx
  src/components/common/Header/Header.tsx
Labels: Feature

#197 ✨feat: 검색기능 추가
  src/components/common/Header/Header.tsx
  src/components/common/SearchBar/SearchBar.stories.tsx
  src/components/common/SearchBar/SearchBar.tsx
  src/components/common/SearchBar/icon_search.svg
  src/components/common/SearchBar/index.tsx
  src/components/common/SearchBar/style.tsx
  src/components/home/Filter/index.tsx
  src/components/home/HomeFilter/HomeFilter.tsx
  src/components/home/HomeFilter/index.tsx
  src/components/home/HomeFilter/style.tsx
  src/components/search/SearchFilter/SearchFilter.tsx
  src/components/search/SearchFilter/index.tsx
  src/components/search/SearchFilter/style.tsx
  src/components/search/index.tsx
  src/pages/home/home.tsx
  src/pages/search/search.tsx
Labels: Feature, 남경

#213 ✨ feat: 수정페이지 navigate 구현
  src/components/common/Textarea/Textarea.tsx
  src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
  src/pages/detail/detail.tsx
  src/pages/detail/index.tsx
Labels: Feature, 형진

#211 ✨ feat: card 사이즈 고정, date 수정
  src/components/common/Card/Card.tsx
  src/components/common/Card/style.tsx
Labels: Feature

#208 ✨ feat: create 서버통신 구현
  src/components/create/DatePicker/DatePicker.tsx
  src/components/create/PartBox/PartBox.jsx
  src/components/create/Select/Select.tsx
  src/components/create/SelectBox/SelectBox.tsx
  src/components/create/SelectBox/style.tsx
  src/pages/create/create.tsx
Labels: Feature

#212 ✨ feat: EditPassword 컴포넌트 구현
  src/components/common/Input/Input.tsx
  src/components/profile/EditPassword/EditPassword.tsx
  src/components/profile/EditPassword/index.tsx
  src/components/profile/EditPassword/style.tsx
  src/components/profile/Modal/index.tsx
  src/components/profile/index.tsx
  src/hooks/index.tsx
  src/hooks/useEditForm.ts
  src/pages/profile/profile.tsx
Labels: Feature

#210 🐛 fix: 로그인 페이지 에러 형식 확인 후 API 요청으로 수정
  src/hooks/useSignIn.tsx
  src/pages/signIn/signIn.tsx
  src/pages/signIn/style.tsx
Labels: Bug

#221 ✨ feat: 수정 서버 통신 구현
  src/components/create/Cascader/Cascader.jsx
  src/components/create/PartBox/PartBox.jsx
  src/pages/edit/edit.tsx
Labels: Feature

#226 ✨ feat: 상세 페이지 post 삭제, 좋아요, 권한 작업
  src/components/detail/PostBody/PostBody.tsx
  src/components/detail/PostFooter/Comment/Comment.tsx
  src/components/detail/PostFooter/PostFooter.tsx
  src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
  src/components/detail/PostHeader/PostHeader.tsx
  src/pages/detail/detail.tsx
Labels: Feature, 형진

#222 ✨ feat: 회원 가입 페이지 구현
  src/components/signUp/index.tsx
  src/hooks/useSignUp.tsx
  src/pages/signUp.tsx
  src/pages/signUp/index.tsx
  src/pages/signUp/signUp.tsx
  src/pages/signUp/style.tsx
  src/routes/Router.tsx
Labels: Feature

#224 ✨feat: contextAPI연결
  src/components/common/Header/Header.tsx
  src/components/common/TempLogin/index.tsx
  src/contexts/AuthProvider.tsx
  src/pages/home/home.tsx
  src/pages/search/search.tsx
Labels: Feature, 남경

#223 ✨ feat: FollowIcon 컴포넌트 구현
  src/assets/icons/icon_create_follow.svg
  src/assets/icons/icon_delete_follow.svg
  src/components/profile/FollowIcon/CreateFollowIcon.tsx
  src/components/profile/FollowIcon/DeleteFollowIcon.tsx
  src/components/profile/FollowIcon/FollowIcon.tsx
  src/components/profile/FollowIcon/index.ts
  src/components/profile/FollowIcon/style.ts
  src/components/profile/ProfileImageBox/index.tsx
  src/components/profile/index.tsx
  src/pages/profile/profile.tsx
Labels: Feature

#227 🐛 fix: DatePicker bug 수정
  src/components/create/DatePicker/DatePicker.tsx
  src/pages/create/create.tsx
  src/pages/edit/edit.tsx
Labels: Bug

#234 💄 style: 생성페이지 css 수정
  src/components/create/Cascader/Cascader.jsx
  src/components/create/PartBox/PartBox.jsx
  src/components/create/PartBox/style.tsx
  src/components/create/SelectBox/style.tsx
  src/pages/create/create.tsx
  src/pages/create/style.tsx
Labels: Feature

#237 :lipstick: style: 수정페이지 css 작업
  src/pages/create/create.tsx
  src/pages/edit/edit.tsx
  src/pages/edit/style.tsx
Labels: Feature

#238 ✨ feat: 댓글 등록 시 알림 생성
  src/components/detail/PostBody/PostBody.tsx
  src/components/detail/PostBody/style.tsx
  src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
  src/pages/detail/detail.tsx
Labels: Feature, 형진, 우선순위: 급함

#243 🐛 fix: [상세페이지] 프로필 사진 조회, 댓글 등록 기능 fix
  src/components/detail/PostFooter/Comment/Comment.tsx
  src/components/detail/PostFooter/PostFooter.tsx
  src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
  src/components/detail/PostHeader/PostHeader.tsx
  src/pages/detail/detail.tsx
Labels: Bug, 형진, 우선순위: 급함

#253 ✨ feat: 수정페이지 ImageUploader 구현
  src/components/create/index.ts
  src/components/create/index.tsx
  src/pages/create/create.tsx
  src/pages/create/index.ts
  src/pages/create/style.ts
  src/pages/edit/edit.tsx
  src/pages/edit/index.ts
  src/pages/edit/style.ts
Labels: Feature

#244 ✨ feat: 유저 정보에 서버 API 및 context 연결
  src/components/common/Card/Card.tsx
  src/components/common/LikeBtn/LikeBtn.tsx
  src/components/common/LikeBtn/style.tsx
  src/components/profile/index.tsx
  src/pages/profile/profile.tsx
Labels: Feature

#241 ✨ feat: 알림기능 dropDown
  src/components/common/DropDown/DropDown.tsx
  src/components/common/DropDown/style.tsx
  src/components/common/Header/Header.tsx
  src/utils/apis/notification.ts
Labels: Feature, 남경

#254 ✨ feat: 상세페이지 프로필 사진 클릭 시 해당 유저 프로필 페이지로 이동
  src/components/detail/PostFooter/Comment/Comment.tsx
  src/components/detail/PostFooter/PostFooter.tsx
  src/components/detail/PostHeader/PostHeader.tsx
  src/pages/detail/detail.tsx
Labels: Feature, 형진, 우선순위: 중간

#242 ♻️ refactor: 로그인, 회원가입 페이지 useForm으로 리팩토링
  src/hooks/useForm.ts
  src/hooks/useSignIn.tsx
  src/hooks/useSignUp.tsx
  src/pages/signIn/signIn.tsx
  src/pages/signUp/signUp.tsx
Labels: Refactor

#256 ✨ feat: 포스트 목록 더보기 기능 구현
  src/pages/profile/profile.tsx
  src/pages/profile/style.tsx
Labels: Feature

#257 :wrench: config: meta 태그 설정
  public/favicon.ico
  public/favicon.svg
  public/index.html
  public/logo.svg
  public/logo192.png
  public/manifest.json
Labels: Feature

#279 ♻️ refactor: Edit / Create 리팩토링
  src/components/create/Cascader/Cascader.jsx
  src/components/create/Cascader/index.ts
  src/components/create/DatePicker/DatePicker.tsx
  src/components/create/DatePicker/index.ts
  src/components/create/ImageUploader/ImageUploader.tsx
  src/components/create/ImageUploader/style.ts
  src/components/create/InputBox/style.ts
  src/components/create/PartBox/index.ts
  src/components/create/PartBox/style.ts
  src/components/create/PartBoxList/index.ts
  src/components/create/PartBoxList/style.ts
  src/components/create/Select/Select.tsx
  src/components/create/Select/index.ts
  src/components/create/SelectBox/SelectBox.tsx
  src/components/create/SelectBox/index.ts
  src/components/create/SelectBox/style.ts
  src/components/edit/index.tsx
  src/pages/create/create.tsx
  src/pages/detail/index.ts
  src/pages/edit/edit.tsx
Labels: Refactor

#278 ♻️ refactor: search, home, pageNotfound 페이지 폴더명 변경
  src/components/home/HomeFilter/index.ts
  src/components/home/HomeFilter/index.tsx
  src/components/home/HomeFilter/style.ts
  src/components/home/index.ts
  src/components/home/index.tsx
  src/components/search/SearchFilter/index.ts
  src/components/search/SearchFilter/index.tsx
  src/components/search/SearchFilter/style.ts
  src/components/search/index.ts
  src/components/search/index.tsx
  src/pages/NotFound/index.ts
  src/pages/NotFound/index.tsx
  src/pages/NotFound/style.ts
  src/pages/home/index.ts
  src/pages/home/style.ts
  src/pages/search/index.ts
  src/pages/search/style.ts
Labels: Refactor

#281 ♻️ refactor: common 컴포넌트 확장자 변경
  src/assets/icons/icon_search.svg
  src/assets/imgs/defaultProfileImage.png
  src/components/404/index.tsx
  src/components/common/AppLayout/index.ts
  src/components/common/AppLayout/style.ts
  src/components/common/Button/index.ts
  src/components/common/Button/style.ts
  src/components/common/Card/index.ts
  src/components/common/Card/style.ts
  src/components/common/DropDown/index.ts
  src/components/common/DropDown/style.ts
  src/components/common/ErrorMessage/index.ts
  src/components/common/ErrorMessage/style.ts
  src/components/common/Footer/index.ts
  src/components/common/Footer/style.ts
  src/components/common/Header/index.ts
  src/components/common/Header/style.ts
  src/components/common/ImageUpload/ImageUpload.tsx
  src/components/common/ImageUpload/index.tsx
  src/components/common/Input/index.ts
  src/components/common/Input/style.ts
  src/components/common/Label/index.ts
  src/components/common/Label/style.ts
  src/components/common/LikeBtn/index.ts
  src/components/common/LikeBtn/style.ts
  src/components/common/PageLoading/index.ts
  src/components/common/PageLoading/style.ts
  src/components/common/ProfileImage/ProfileImage.tsx
  src/components/common/ProfileImage/index.ts
  src/components/common/ProfileImage/style.ts
  src/components/common/SearchBar/SearchBar.tsx
  src/components/common/SearchBar/index.ts
  src/components/common/SearchBar/style.ts
  src/components/common/SkillIcon/SkillIcon.tsx
  src/components/common/SkillIcon/index.ts
  src/components/common/SkillIcon/style.ts
  src/components/common/Textarea/index.ts
  src/components/common/Textarea/style.ts
Labels: Refactor

#292 🐛 fix: pageNotFound 페이지 파일명 변경
  src/pages/NotFound/index.ts
  src/pages/pagenotfound/index.ts
  src/pages/pagenotfound/pagenotfound.tsx
  src/pages/pagenotfound/style.ts
  src/routes/Router.tsx
Labels: 우선순위: 급함, HotFix

#285 🐛 fix: detail QA사항 반영
  src/components/detail/PostHeader/PostHeader.tsx
  src/components/detail/TextareaBox/TextareaBox.tsx
  src/pages/detail/detail.tsx
Labels: Bug, 형진, 우선순위: 중간

#290 :bug: fix: edit page select defaultValue 설정
  src/pages/create/create.tsx
  src/pages/edit/edit.tsx
Labels: HotFix

#295 🐛 fix: 글 생성, 수정 이후 메인페이지 navigate 안 되던 버그 수정
  src/pages/create/create.tsx
  src/pages/edit/edit.tsx
Labels: HotFix

#296 💄 style: 메인 스타일 수정
  src/assets/imgs/main_banner.png
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/style.ts
  src/components/common/Header/Header.tsx
  src/components/common/Header/style.ts
  src/components/home/Banner/Banner.tsx
  src/components/home/Banner/index.tsx
  src/components/home/Banner/style.tsx
  src/pages/home/home.tsx
  src/pages/home/style.ts
  src/pages/search/search.tsx
  src/pages/search/style.ts
Labels: Feature

#297 :wrench: config: 불필요한 eslintConfig 삭제 후 .eslintrc.json으로 통일
  .eslintrc.json
  package.json
  src/components/detail/TextareaBox/TextareaBox.tsx
Labels: Feature

#305 ✨ feat: SettingDropDown 컴포넌트 구현
  src/components/common/index.ts
  src/components/profile/CoverImageBox/CoverImageBox.tsx
  src/components/profile/ProfileImageBox/ProfileImageBox.tsx
  src/components/profile/SettingDropDown/SettingDropDown.tsx
  src/components/profile/SettingDropDown/index.ts
  src/components/profile/SettingDropDown/style.ts
  src/components/profile/index.ts
  src/pages/profile/profile.tsx
Labels: Feature

#308 🐛 bug: 로그인 상태에서 로그인, 회원가입 페이지 접근 시 메인으로 돌리기
  src/pages/signIn/signIn.tsx
  src/pages/signUp/signUp.tsx
Labels: Bug

#307 ✨ feat: BottomSheet 컴포넌트 구현
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/common/BottomSheet/index.ts
  src/components/common/BottomSheet/style.ts
  src/components/common/Footer/Footer.tsx
  src/components/common/Textarea/style.ts
  src/components/common/User/User.tsx
  src/components/common/UserSearchBar/UserSearchBar.tsx
Labels: Feature, 형진, 우선순위: 급함

#311 ♻️ refactor: InputBox common 폴더로 이동
  src/components/common/InputBox/Index.ts
  src/components/common/InputBox/InputBox.stories.tsx
  src/components/common/InputBox/InputBox.tsx
  src/components/common/InputBox/style.ts
  src/components/create/index.ts
  src/pages/signIn/signIn.tsx
  src/pages/signUp/signUp.tsx
Labels: Refactor

#319 ♻️ refactor: home, search 페이지 경로별칭 수정
  src/components/common/Header/Header.tsx
  src/components/common/LikeBtn/LikeBtn.tsx
  src/components/home/HomeFilter/HomeFilter.tsx
  src/components/search/SearchFilter/SearchFilter.tsx
Labels: Refactor

#321 ♻️ refactor: 로그인, 회원가입, InputBox, Context 경로별칭 수정
  src/components/common/InputBox/InputBox.tsx
  src/components/common/InputBox/style.ts
  src/contexts/AuthProvider.tsx
  src/pages/signIn/signIn.tsx
  src/pages/signUp/signUp.tsx
Labels: Refactor

#320 ♻️ refactor: TampLogin 컴포넌트 제거
  src/components/common/Header/Header.tsx
  src/components/common/TempLogin/index.tsx
Labels: Refactor

#322 ♻️ refactor: 상세보기 페이지 경로 별칭 수정
  src/components/detail/Comment/Comment.tsx
  src/components/detail/PostBody/PostBody.tsx
  src/components/detail/PostFooter/PostFooter.tsx
  src/components/detail/PostHeader/PostHeader.tsx
  src/components/detail/PostSummary/PostSummary.tsx
  src/components/detail/TextareaBox/TextareaBox.tsx
Labels: Refactor, 형진, 우선순위: 중간

#324 ♻️ refactor: 생성/편집 페이지 경로 별칭 수정
  src/components/create/index.ts
Labels: Refactor, 형진, 우선순위: 중간

#326 ✨ feat: 닉네임 변경 context api 연결
  src/components/profile/EditFullName/EditFullName.tsx
  src/components/profile/EditPassword/EditPassword.tsx
  src/components/profile/SettingDropDown/SettingDropDown.tsx
  src/hooks/useEditForm.ts
  src/pages/profile/profile.tsx
Labels: Feature

#330 🐛 fix: 비로그인상태에서는 edit / create 페이지 접근 못 하도록 수정
  src/pages/create/create.tsx
  src/pages/edit/edit.tsx
Labels: HotFix

#332 🐛 fix: BottomSheet hide 상태에서 스크롤 이벤트 방지 처리
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/common/BottomSheet/style.ts
  src/components/common/UserSearchBar/UserSearchBar.tsx
  src/components/common/UserSearchBar/index.ts
  src/components/common/UserSearchBar/style.ts
Labels: 형진, 우선순위: 급함, HotFix

#337 🐛 fix: 상세페이지 게시글 좋아요 영역에 비회원은 cursor: default 처리
  src/components/detail/PostHeader/PostHeader.tsx
Labels: 형진, 우선순위: 급함, HotFix

#336 🐛 fix: 검색기능 수정
  src/pages/search/search.tsx
Labels: Bug

#334 :sparkles: feat: validation 통과 못 할 경우 alert메시지 출력
  src/pages/create/create.tsx
Labels: Feature

#335 ✨ feat: 프로필 페이지 로딩 추가
  src/pages/profile/profile.tsx
  src/pages/profile/style.ts
Labels: Feature

#339 🐛 fix: 사용자 검색 조건 필터를 equal에서 like로 변경, 엔터로 검색 추가, BottomSheet 페이지 별로 show/hide 처리
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/common/Footer/Footer.tsx
Labels: 형진, 우선순위: 급함, HotFix

#344 🐛 fix: 상세 페이지 이전 페이지로 뒤로가기로 변경, 사용자 검색 안되는 버그 조치
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/detail/PostHeader/PostHeader.tsx
  src/pages/detail/detail.tsx
Labels: 형진, 우선순위: 급함, HotFix

#346 🐛 fix: 상세 페이지 ai 채널 조회 대문자에서 소문자로 변경
  src/pages/detail/detail.tsx
Labels: 형진, 우선순위: 급함, HotFix

#347 ✨ feat: Reward 컴포넌트 구현
  src/assets/icons/icon_reward_comment.svg
  src/assets/icons/icon_reward_cover.svg
  src/assets/icons/icon_reward_follow.svg
  src/assets/icons/icon_reward_love.svg
  src/assets/icons/icon_reward_post.svg
  src/assets/icons/icon_reward_profile.svg
  src/components/profile/Reward/Reward.tsx
  src/components/profile/Reward/index.ts
  src/components/profile/Reward/style.ts
  src/components/profile/index.ts
  src/pages/profile/profile.tsx
  src/pages/profile/style.ts
Labels: Feature

#348 🐛 fix: 업적 기준이 0으로 설정된 문제
  src/pages/profile/profile.tsx
Labels: HotFix
